/* global YT */
(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const STORAGE_KEY = 'priconner-clan-battle-trainer:v1';
  const state = { player: null, localVideo: $('local-video'), magnifierVideo: $('magnifier-video'), ready: false, mode: 'none', magnifier: false, videoId: '', localObjectUrl: '', localFileName: '', rows: [], logs: [], activeRowId: null, preview: null, practice: null, duration: 0, currentTime: 0, reverseTimer: null, reversePractice: false, pendingYouTubePlayUntil: 0, beepTimer: null, audio: null };
  const isHttpPage = () => window.location.protocol === 'http:' || window.location.protocol === 'https:';
  const fps = () => Math.max(1, Number.parseFloat($('fps').value) || 60);
  const frameAt = (seconds) => Math.max(0, Math.floor(seconds * fps()));
  const formatTime = (seconds) => { const s = Math.max(0, Number(seconds) || 0); return `${String(Math.floor(s / 60)).padStart(2, '0')}:${(s % 60).toFixed(3).padStart(6, '0')}`; };
  const id = (prefix) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
  const getVideoId = (value) => { try { const url = new URL(value); if (url.hostname === 'youtu.be') return url.pathname.slice(1).split('/')[0]; if (url.hostname.endsWith('youtube.com')) return url.searchParams.get('v') || url.pathname.match(/\/shorts\/([^/]+)/)?.[1] || url.pathname.match(/\/embed\/([^/]+)/)?.[1] || ''; } catch (_) {} return ''; };
  const setStatus = (message, error = false) => { $('status').textContent = message; $('status').style.color = error ? 'var(--bad)' : ''; };
  const setSourceBadge = (label) => { $('source-badge').textContent = label; $('source-badge').dataset.mode = state.mode; };
  function persist() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify({ version: 1, video: { url: $('video-url').value, fps: fps(), speed: Number($('speed').value), beep: $('beep-enabled').checked }, notes: $('notes').value, rows: state.rows, logs: state.logs })); } catch (_) { setStatus('ブラウザ保存に失敗しました', true); } }
  function restore() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'); if (!saved) return false; $('video-url').value = saved.video?.url || ''; $('fps').value = saved.video?.fps || 60; $('speed').value = String(saved.video?.speed || 1); $('beep-enabled').checked = Boolean(saved.video?.beep); $('notes').value = saved.notes || ''; state.rows = Array.isArray(saved.rows) ? saved.rows : []; state.logs = Array.isArray(saved.logs) ? saved.logs : []; return true; } catch (_) { localStorage.removeItem(STORAGE_KEY); return false; } }

  window.onYouTubeIframeAPIReady = () => { state.apiReady = true; setStatus('YouTube API準備完了。URLを入力してください'); };
  function createPlayer(videoId) {
    if (state.player) state.player.destroy();
    state.mode = 'youtube'; setSourceBadge('YouTube'); state.localVideo.hidden = true; state.localVideo.pause(); state.localVideo.removeAttribute('src'); updateMagnifier();
    const playerVars = { playsinline: 1, rel: 0, controls: 0, autoplay: 1, mute: 1, enablejsapi: 1 };
    if (isHttpPage()) playerVars.origin = window.location.origin;
    state.player = new YT.Player('player', { videoId, playerVars, events: { onReady: onPlayerReady, onStateChange: onPlayerStateChange, onError: (event) => setStatus(`動画を再生できません（YouTubeエラー ${event.data}）`, true) } });
  }
  function onPlayerReady(event) {
    state.ready = true; state.mode = 'youtube'; setSourceBadge('YouTube'); state.duration = event.target.getDuration() || 0; event.target.setVolume(Number($('volume').value));
    $('duration').textContent = formatTime(state.duration); $('video-title').textContent = event.target.getVideoData()?.title || '動画'; $('video-info').textContent = `再生時間 ${formatTime(state.duration)} / 推定フレーム ${Math.round(state.duration * fps()).toLocaleString()}`; event.target.mute(); event.target.playVideo(); setStatus('準備完了'); render();
  }
  function onPlayerStateChange(event) { $('play').textContent = event.data === YT.PlayerState.PLAYING ? 'Ⅱ 一時停止' : '▶ 再生'; if (event.data === YT.PlayerState.PLAYING) startTicker(); else stopTicker(); if (event.data === YT.PlayerState.ENDED && state.practice) loopPractice(); else if (state.practice && Date.now() < state.pendingYouTubePlayUntil && [YT.PlayerState.BUFFERING, YT.PlayerState.CUED, YT.PlayerState.PAUSED].includes(event.data)) window.setTimeout(() => { if (state.practice && Date.now() < state.pendingYouTubePlayUntil) state.player.playVideo(); }, 100); }
  function onLocalLoaded() { state.ready = true; state.mode = 'local'; setSourceBadge('ローカル'); state.duration = state.localVideo.duration || 0; state.magnifierVideo.src = state.localObjectUrl; state.magnifierVideo.load(); updateMagnifier(); $('duration').textContent = formatTime(state.duration); $('video-title').textContent = state.localFileName || 'ローカル動画'; $('video-info').textContent = `再生時間 ${formatTime(state.duration)} / 推定フレーム ${Math.round(state.duration * fps()).toLocaleString()}`; setStatus('ローカル動画の準備完了'); render(); }
  function onLocalStateChange() { $('play').textContent = state.localVideo.paused ? '▶ 再生' : 'Ⅱ 一時停止'; if (state.localVideo.paused) { stopTicker(); state.magnifierVideo.pause(); } else { startTicker(); syncMagnifierVideo(true); } }
  function loadLocalVideo(file) { if (!file || !file.type.startsWith('video/')) return setStatus('動画ファイルを選択してください', true); if (state.player) { state.player.destroy(); state.player = null; } if (state.localObjectUrl) URL.revokeObjectURL(state.localObjectUrl); state.ready = false; state.practice = null; state.localFileName = file.name; state.localObjectUrl = URL.createObjectURL(file); state.localVideo.hidden = false; state.localVideo.src = state.localObjectUrl; state.magnifierVideo.src = state.localObjectUrl; state.magnifierVideo.load(); state.localVideo.load(); setStatus('ローカル動画を読み込み中…'); }
  function syncMagnifierVideo(play = false) { if (!state.magnifierVideo || !state.localObjectUrl || state.mode !== 'local') return; try { if (Math.abs((state.magnifierVideo.currentTime || 0) - state.currentTime) > 0.08) state.magnifierVideo.currentTime = state.currentTime; if (play) state.magnifierVideo.play().catch(() => {}); } catch (_) {} }
  function setMagnifierPosition(event) { if (!state.magnifier || state.mode !== 'local') return; const wrap = document.querySelector('.video-wrap'); const videoRect = state.localVideo.getBoundingClientRect(); const wrapRect = wrap.getBoundingClientRect(); const size = 180; const scale = Number($('magnifier-scale').value) || 2; const x = Math.max(0, Math.min(videoRect.width, event.clientX - videoRect.left)); const y = Math.max(0, Math.min(videoRect.height, event.clientY - videoRect.top)); const left = Math.max(0, Math.min(wrapRect.width - size, event.clientX - wrapRect.left - size / 2)); const top = Math.max(0, Math.min(wrapRect.height - size, event.clientY - wrapRect.top - size / 2)); const lens = $('magnifier'); lens.style.left = `${left}px`; lens.style.top = `${top}px`; state.magnifierVideo.style.width = `${videoRect.width * scale}px`; state.magnifierVideo.style.height = `${videoRect.height * scale}px`; state.magnifierVideo.style.left = `${size / 2 - x * scale}px`; state.magnifierVideo.style.top = `${size / 2 - y * scale}px`; syncMagnifierVideo(); }
  function updateMagnifier() { const lens = $('magnifier'); const enabled = state.magnifier && state.mode === 'local'; lens.hidden = !enabled; document.querySelector('.video-wrap').classList.toggle('youtube-zoom', state.magnifier && state.mode === 'youtube'); document.querySelector('.video-wrap').style.setProperty('--magnifier-scale', $('magnifier-scale').value); $('magnifier-toggle').textContent = state.magnifier ? '🔍 虫眼鏡ON' : '🔍 虫眼鏡'; if (enabled) { const rect = state.localVideo.getBoundingClientRect(); setMagnifierPosition({ clientX: rect.left + rect.width / 2, clientY: rect.top + rect.height / 2 }); syncMagnifierVideo(!state.localVideo.paused); } else state.magnifierVideo.pause(); }
  function toggleMagnifier() { state.magnifier = !state.magnifier; updateMagnifier(); if (state.magnifier) setStatus(state.mode === 'youtube' ? 'プレーヤー全体を拡大表示中' : 'ポインタ位置を拡大表示中'); else setStatus('虫眼鏡をOFFにしました'); }
  let ticker;
  function startTicker() { if (!ticker) ticker = window.setInterval(updatePosition, 50); }
  function stopTicker() { window.clearInterval(ticker); ticker = null; }
  function updatePosition() {
    if (!state.ready) return; state.currentTime = mediaTime(); const current = frameAt(state.currentTime); const target = activeTarget(); $('loop-practice').textContent = state.practice ? '■ ループ停止' : '↻ ループ再生';
    $('time-readout').textContent = formatTime(state.currentTime); $('frame-readout').textContent = current.toLocaleString(); $('frame-context').textContent = current.toLocaleString(); $('target-context').textContent = target == null ? '—' : target.toLocaleString(); $('delta-context').textContent = target == null ? '—' : signed(current - target);
    const pct = state.duration ? Math.min(100, state.currentTime / state.duration * 100) : 0; $('progress-fill').style.width = `${pct}%`; const marker = target == null || !state.duration ? null : target / fps() / state.duration * 100; $('target-marker').style.display = marker == null ? 'none' : 'block'; if (marker != null) $('target-marker').style.left = `${Math.min(100, marker)}%`;
    if (state.practice && !state.practice.looping && state.currentTime >= state.practice.end) loopPractice();
    if (state.mode === 'local' && state.magnifier) syncMagnifierVideo(!state.localVideo.paused);
    if ($('beep-enabled').checked) tickBeep(current);
  }
  const signed = (value) => `${value > 0 ? '+' : ''}${value}f`;
  function activeTarget() { return state.rows.find((row) => row.id === state.activeRowId)?.frame ?? null; }
  function loadVideo() { if (!isHttpPage()) return setStatus('file://直開きではYouTubeを再生できません。READMEのHTTP起動方法を使ってください', true); const videoId = getVideoId($('video-url').value.trim()); if (!videoId) return setStatus('YouTube URLを確認してください', true); state.videoId = videoId; createPlayer(videoId); setStatus('動画を読み込み中…'); }
  function mediaTime() { return state.mode === 'local' ? state.localVideo.currentTime || 0 : state.player.getCurrentTime() || 0; }
  function mediaSeek(seconds, play = false) { if (!state.ready) return; const target = Math.max(0, Math.min(state.duration || Infinity, seconds)); if (state.mode === 'local') { state.localVideo.currentTime = target; if (play) state.localVideo.play().catch(() => setStatus('再生には動画画面の操作が必要です', true)); else state.localVideo.pause(); } else { state.player.seekTo(target, true); if (play) state.player.playVideo(); else { state.player.pauseVideo(); window.setTimeout(() => state.player.pauseVideo(), 120); } } updatePosition(); window.setTimeout(updatePosition, 250); }
  function seek(seconds, play = false) { mediaSeek(seconds, play); }
  function resumePracticePlayback(attempt = 0) { if (!state.practice || !state.ready) return; state.practice.looping = false; const before = state.mode === 'local' ? state.localVideo.currentTime : state.player.getCurrentTime(); startTicker(); if (state.mode === 'local') { state.localVideo.play().catch(() => {}); } else { state.pendingYouTubePlayUntil = Date.now() + 5000; state.player.playVideo(); } if (attempt < 12) window.setTimeout(() => { if (!state.practice || !state.ready) return; const current = state.mode === 'local' ? state.localVideo.currentTime : state.player.getCurrentTime(); const playing = state.mode === 'local' ? !state.localVideo.paused : state.player.getPlayerState() === YT.PlayerState.PLAYING; const advanced = Math.abs(current - before) > 0.03; if (!playing || !advanced) resumePracticePlayback(attempt + 1); }, 250); }
  const jumpSeconds = (seconds) => { if (!state.ready) return setStatus('動画を読み込んでください', true); const looping = Boolean(state.practice); const nextTime = looping ? Math.max(0, state.currentTime + seconds) : state.currentTime + seconds; seek(nextTime, looping); if (looping) { resumePracticePlayback(); window.setTimeout(resumePracticePlayback, 120); } };
  function loopPractice() { if (!state.practice || !state.ready || state.practice.looping) return; state.practice.looping = true; mediaSeek(state.practice.start); if (state.mode === 'local') state.localVideo.play().catch(() => {}); else { state.pendingYouTubePlayUntil = Date.now() + 1500; state.player.playVideo(); } window.setTimeout(() => { if (state.practice) state.practice.looping = false; }, 250); }
  function togglePlay() { if (!state.ready) return; if (state.mode === 'local') { state.localVideo.paused ? state.localVideo.play().catch(() => {}) : state.localVideo.pause(); } else { const playing = state.player.getPlayerState() === YT.PlayerState.PLAYING; playing ? state.player.pauseVideo() : state.player.playVideo(); } }
  function pauseMedia() { if (state.mode === 'local') state.localVideo.pause(); else state.player.pauseVideo(); }
  function step(direction) { if (!state.ready) return; const looping = Boolean(state.practice); if (!looping) pauseMedia(); const nextTime = looping ? Math.max(0, state.currentTime + direction / fps()) : state.currentTime + direction / fps(); seek(nextTime, looping); if (looping) { resumePracticePlayback(); window.setTimeout(resumePracticePlayback, 120); } }
  function startReverse() { if (!state.ready) return; pauseMedia(); state.reversePractice = Boolean(state.practice); window.clearInterval(state.reverseTimer); state.reverseTimer = window.setInterval(() => { if (state.currentTime <= 0) return stopReverse(); seek(Math.max(0, state.currentTime - 1 / fps())); }, 1000 / 4); }
  function stopReverse(resumePractice = true) { const shouldResume = resumePractice && state.reversePractice && Boolean(state.practice); window.clearInterval(state.reverseTimer); state.reverseTimer = null; state.reversePractice = false; if (shouldResume) resumePracticePlayback(); }
  function changeSpeed(delta) { const select = $('speed'); const values = [...select.options].map((o) => Number(o.value)); const next = values[Math.max(0, Math.min(values.length - 1, values.indexOf(Number(select.value)) + delta))]; select.value = next; if (state.ready) state.mode === 'local' ? (state.localVideo.playbackRate = next) : state.player.setPlaybackRate(next); }
  function capture() { if (!state.ready) return setStatus('動画を読み込んでください', true); state.currentTime = mediaTime(); const actualFrame = frameAt(state.currentTime); const targetFrame = activeTarget(); const log = { id: id('log'), rowId: state.activeRowId, targetFrame, actualFrame, delta: targetFrame == null ? null : actualFrame - targetFrame, createdAt: new Date().toISOString() }; state.logs.unshift(log); renderLogs(); persist(); setStatus(targetFrame == null ? `${actualFrame}f を記録しました` : `${actualFrame}f / 目標との差 ${signed(log.delta)}`); beep(880, .09); }
  function startPractice(rowId, autoplay = true) { state.activeRowId = rowId; const frame = state.rows.find((row) => row.id === rowId)?.frame; if (frame == null) return; stopReverse(false); const start = Math.max(0, (frame - 5 * fps()) / fps()); state.preview = null; state.practice = { rowId, start, end: (frame + 2 * fps()) / fps(), looping: false }; seek(start); if (autoplay) { resumePracticePlayback(); window.setTimeout(resumePracticePlayback, 120); } renderRows(); if (autoplay) setStatus(`目標 ${frame}f のループ再生を開始しました`); }
  function stopPractice() { state.practice = null; state.preview = null; state.activeRowId = null; stopReverse(false); render(); setStatus('練習対象を解除しました'); }
  function togglePracticeLoop() { if (!state.ready) return setStatus('動画を読み込んでください', true); if (state.practice) return stopPractice(); const rowId = state.activeRowId || state.preview?.rowId; const row = state.rows.find((candidate) => candidate.id === rowId); if (!row || row.frame == null) return setStatus('先に目標行を選択してください', true); startPractice(row.id, true); }
  function addRow(label = '新しい目標', frame = '') { const row = { id: id('row'), label, frame: frame === '' ? null : Number(frame) }; state.rows.push(row); state.activeRowId = row.id; renderRows(); }
  function addCurrentFrameRow() { if (!state.ready) return setStatus('動画を読み込んでください', true); const current = frameAt(state.currentTime); addRow(`現在 ${formatTime(state.currentTime)}`, current); persist(); setStatus(`現在のフレーム ${current}f を目標に追加しました`); }
  function parseNotesToRows() { const lines = $('notes').value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); const parsed = lines.map((label) => { const frameMatch = label.match(/(?:^|\s)(\d+)\s*f\b/i); if (frameMatch) return { label, frame: Number(frameMatch[1]) }; const timeMatch = label.match(/(?:^|\s)(\d{1,3}):(\d{2})(?:\.(\d+))?/); if (!timeMatch) return { label, frame: null }; const seconds = Number(timeMatch[1]) * 60 + Number(timeMatch[2]) + Number(`0.${timeMatch[3] || 0}`); return { label, frame: Math.round(seconds * fps()) }; }); if (!parsed.length) return setStatus('TLの行がありません', true); state.rows.push(...parsed.map((row) => ({ id: id('row'), ...row }))); state.activeRowId = state.rows.at(-1).id; persist(); renderRows(); setStatus(`${parsed.length}行を目標行として追加しました`); }
  function handleRowTap(row) { if (!state.ready) return setStatus('先に動画を読み込んでください', true); const displayedFrame = frameAt(mediaTime()); if (row.frame == null) { row.frame = displayedFrame; state.activeRowId = row.id; state.preview = { rowId: row.id, frame: row.frame }; state.practice = null; seek(row.frame / fps()); persist(); renderRows(); setStatus(`現在のフレーム ${row.frame}f を登録して停止表示しました`); return; } const isSamePreview = state.preview?.rowId === row.id && state.preview.frame === row.frame && state.activeRowId === row.id; if (isSamePreview) return startPractice(row.id, true); state.activeRowId = row.id; state.preview = { rowId: row.id, frame: row.frame }; state.practice = null; seek(row.frame / fps()); renderRows(); setStatus(`登録フレーム ${row.frame}f を停止表示しました`); }
  function renderRows() { const root = $('tl-list'); root.innerHTML = ''; state.rows.forEach((row) => { const item = document.createElement('div'); item.className = `tl-row${row.id === state.activeRowId ? ' active' : ''}`; const label = document.createElement('button'); label.textContent = row.label || '（無題）'; label.title = row.frame == null ? '現在フレームを登録して停止表示' : '1回目: フレーム表示 / 2回目: ループ再生'; label.onclick = () => handleRowTap(row); const frame = document.createElement('input'); frame.type = 'number'; frame.min = '0'; frame.placeholder = '目標f'; frame.value = row.frame ?? ''; frame.onchange = () => { row.frame = frame.value === '' ? null : Number(frame.value); state.preview = null; persist(); render(); }; const remove = document.createElement('button'); remove.className = 'remove'; remove.textContent = '×'; remove.title = '行を削除'; remove.onclick = () => { state.rows = state.rows.filter((candidate) => candidate.id !== row.id); if (state.activeRowId === row.id) { state.activeRowId = null; state.preview = null; state.practice = null; } persist(); render(); }; item.append(label, frame, remove); root.append(item); }); }
  function renderLogs() { const root = $('log-list'); root.innerHTML = ''; if (!state.logs.length) return root.innerHTML = '<p class="empty">まだログはありません。動画再生中にクリックしてください。</p>'; state.logs.forEach((log) => { const item = document.createElement('div'); item.className = `log-entry ${log.delta != null && Math.abs(log.delta) <= 2 ? 'good' : 'bad'}`; const delta = log.delta == null ? '目標未設定' : signed(log.delta); item.innerHTML = `<div class="log-main"><span>${log.actualFrame.toLocaleString()}f</span><span class="${log.delta != null && Math.abs(log.delta) <= 2 ? 'delta-good' : 'delta-bad'}">${delta}</span></div><div class="log-sub">目標 ${log.targetFrame ?? '—'}f · ${new Date(log.createdAt).toLocaleTimeString('ja-JP')}</div>`; item.onclick = () => { if (log.rowId) handleRowTap(state.rows.find((row) => row.id === log.rowId) || { id: log.rowId, frame: log.targetFrame }); seek(log.actualFrame / fps()); }; root.append(item); }); }
  function render() { renderRows(); renderLogs(); updatePosition(); $('magnifier-toggle').onclick = toggleMagnifier; $('magnifier-scale').onchange = updateMagnifier; if (!state.magnifierBound) { document.querySelector('.video-wrap').addEventListener('pointermove', setMagnifierPosition); state.magnifierBound = true; } updateMagnifier(); }
  function exportData() { const data = { version: 1, video: { url: $('video-url').value, fps: fps() }, notes: $('notes').value, rows: state.rows, logs: state.logs }; const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `priconne-clan-battle-practice-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); }
  function importData(file) { const reader = new FileReader(); reader.onload = () => { try { const data = JSON.parse(reader.result); $('video-url').value = data.video?.url || ''; $('fps').value = data.video?.fps || 60; $('notes').value = data.notes || ''; state.rows = Array.isArray(data.rows) ? data.rows : []; state.logs = Array.isArray(data.logs) ? data.logs : []; state.activeRowId = null; state.preview = null; state.practice = null; render(); persist(); setStatus('JSONを読み込みました'); } catch (_) { setStatus('JSONの読み込みに失敗しました', true); } }; reader.readAsText(file); }
  function beep(frequency = 660, duration = .08) { state.audio ||= new (window.AudioContext || window.webkitAudioContext)(); const oscillator = state.audio.createOscillator(); const gain = state.audio.createGain(); oscillator.frequency.value = frequency; gain.gain.setValueAtTime(.035, state.audio.currentTime); gain.gain.exponentialRampToValueAtTime(.001, state.audio.currentTime + duration); oscillator.connect(gain).connect(state.audio.destination); oscillator.start(); oscillator.stop(state.audio.currentTime + duration); }
  function tickBeep(frame) { const second = Math.floor(state.currentTime); if (state.lastBeepSecond !== second) { state.lastBeepSecond = second; beep(); } }
  $('loop-practice').onclick = togglePracticeLoop;
  $('load-video').onclick = loadVideo; $('local-file').onchange = (event) => loadLocalVideo(event.target.files[0]); $('play').onclick = togglePlay; $('click-capture').onclick = capture; $('back-5').onclick = () => jumpSeconds(-5); $('back-frame').onclick = () => step(-1); $('forward-frame').onclick = () => step(1); $('forward-5').onclick = () => jumpSeconds(5); $('reverse').onmousedown = startReverse; $('reverse').onmouseup = stopReverse; $('reverse').onmouseleave = stopReverse; $('speed-down').onclick = () => changeSpeed(-1); $('speed-up').onclick = () => changeSpeed(1); $('stop-practice').onclick = stopPractice; $('speed').onchange = () => { if (state.ready) state.mode === 'local' ? (state.localVideo.playbackRate = Number($('speed').value)) : state.player.setPlaybackRate(Number($('speed').value)); persist(); }; $('volume').oninput = (event) => { if (!state.ready) return; state.mode === 'local' ? (state.localVideo.volume = Number(event.target.value) / 100) : state.player.setVolume(Number(event.target.value)); }; $('mute').onclick = () => { if (!state.ready) return; if (state.mode === 'local') state.localVideo.muted = !state.localVideo.muted; else state.player.isMuted() ? state.player.unMute() : state.player.mute(); $('mute').textContent = (state.mode === 'local' ? state.localVideo.muted : state.player.isMuted()) ? '🔇' : '🔊'; }; $('add-row').onclick = () => { addRow(); persist(); }; $('add-current-row').onclick = addCurrentFrameRow; $('parse-notes').onclick = parseNotesToRows; $('clear-logs').onclick = () => { state.logs = []; renderLogs(); persist(); }; $('clear-storage').onclick = () => { state.rows = []; state.logs = []; $('video-url').value = ''; $('notes').value = ''; state.activeRowId = null; state.preview = null; state.practice = null; render(); localStorage.removeItem(STORAGE_KEY); setStatus('保存データを削除しました'); }; $('export-button').onclick = exportData; $('import-button').onclick = () => $('import-file').click(); $('import-file').onchange = (event) => event.target.files[0] && importData(event.target.files[0]); $('fps').onchange = () => { persist(); render(); }; $('notes').oninput = persist; $('video-url').oninput = persist; $('beep-enabled').onchange = () => { if (!$('beep-enabled').checked) state.lastBeepSecond = null; persist(); };
  document.addEventListener('keydown', (event) => { if (['INPUT', 'TEXTAREA', 'SELECT'].includes(document.activeElement.tagName)) return; if (event.key === ' ' || event.key.toLowerCase() === 'k') { event.preventDefault(); togglePlay(); } else if (event.key === 'j' || event.key === 'ArrowLeft') step(-1); else if (event.key === 'l' || event.key === 'ArrowRight') step(1); else if (event.key === 'Enter') capture(); else if (event.key.toLowerCase() === 'm') $('mute').click(); else if (event.key.toLowerCase() === 'b') { $('beep-enabled').checked = !$('beep-enabled').checked; } else if (event.shiftKey && event.key.toLowerCase() === 'j') startReverse(); });
  state.localVideo.addEventListener('loadedmetadata', onLocalLoaded); state.localVideo.addEventListener('play', onLocalStateChange); state.localVideo.addEventListener('pause', onLocalStateChange); state.localVideo.addEventListener('ended', () => state.practice ? loopPractice() : stopTicker()); const restored = restore(); window.addEventListener('beforeunload', () => { stopReverse(); if (state.localObjectUrl) URL.revokeObjectURL(state.localObjectUrl); }); setStatus(isHttpPage() ? (restored ? '前回の設定を復元しました。動画を選択してください' : 'YouTube APIを準備中…') : 'file://直開きです。YouTube再生にはHTTP起動が必要です'); renderRows(); renderLogs();
})();
