/* global YT */
(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const state = { player: null, ready: false, videoId: '', rows: [], logs: [], activeRowId: null, practice: null, duration: 0, currentTime: 0, reverseTimer: null, beepTimer: null, audio: null };
  const isHttpPage = () => window.location.protocol === 'http:' || window.location.protocol === 'https:';
  const fps = () => Math.max(1, Number.parseFloat($('fps').value) || 60);
  const frameAt = (seconds) => Math.max(0, Math.round(seconds * fps()));
  const formatTime = (seconds) => { const s = Math.max(0, Number(seconds) || 0); return `${String(Math.floor(s / 60)).padStart(2, '0')}:${(s % 60).toFixed(3).padStart(6, '0')}`; };
  const id = (prefix) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
  const getVideoId = (value) => { try { const url = new URL(value); if (url.hostname === 'youtu.be') return url.pathname.slice(1).split('/')[0]; if (url.hostname.endsWith('youtube.com')) return url.searchParams.get('v') || url.pathname.match(/\/shorts\/([^/]+)/)?.[1] || url.pathname.match(/\/embed\/([^/]+)/)?.[1] || ''; } catch (_) {} return ''; };
  const setStatus = (message, error = false) => { $('status').textContent = message; $('status').style.color = error ? 'var(--bad)' : ''; };

  window.onYouTubeIframeAPIReady = () => { state.apiReady = true; setStatus('YouTube API準備完了。URLを入力してください'); };
  function createPlayer(videoId) {
    if (state.player) state.player.destroy();
    const playerVars = { playsinline: 1, rel: 0, enablejsapi: 1 };
    if (isHttpPage()) playerVars.origin = window.location.origin;
    state.player = new YT.Player('player', { videoId, playerVars, events: { onReady: onPlayerReady, onStateChange: onPlayerStateChange, onError: (event) => setStatus(`動画を再生できません（YouTubeエラー ${event.data}）`, true) } });
  }
  function onPlayerReady(event) {
    state.ready = true; state.duration = event.target.getDuration() || 0; event.target.setVolume(Number($('volume').value));
    $('duration').textContent = formatTime(state.duration); $('video-title').textContent = event.target.getVideoData()?.title || '動画'; $('video-info').textContent = `再生時間 ${formatTime(state.duration)} / 推定フレーム ${Math.round(state.duration * fps()).toLocaleString()}`; setStatus('準備完了'); render();
  }
  function onPlayerStateChange(event) { $('play').textContent = event.data === YT.PlayerState.PLAYING ? 'Ⅱ 一時停止' : '▶ 再生'; if (event.data === YT.PlayerState.PLAYING) startTicker(); else stopTicker(); if (event.data === YT.PlayerState.ENDED && state.practice) loopPractice(); }
  let ticker;
  function startTicker() { if (!ticker) ticker = window.setInterval(updatePosition, 50); }
  function stopTicker() { window.clearInterval(ticker); ticker = null; }
  function updatePosition() {
    if (!state.ready) return; state.currentTime = state.player.getCurrentTime() || 0; const current = frameAt(state.currentTime); const target = activeTarget();
    $('time-readout').textContent = formatTime(state.currentTime); $('frame-readout').textContent = current.toLocaleString(); $('frame-context').textContent = current.toLocaleString(); $('target-context').textContent = target == null ? '—' : target.toLocaleString(); $('delta-context').textContent = target == null ? '—' : signed(current - target);
    const pct = state.duration ? Math.min(100, state.currentTime / state.duration * 100) : 0; $('progress-fill').style.width = `${pct}%`; const marker = target == null || !state.duration ? null : target / fps() / state.duration * 100; $('target-marker').style.display = marker == null ? 'none' : 'block'; if (marker != null) $('target-marker').style.left = `${Math.min(100, marker)}%`;
    if (state.practice && !state.practice.looping && state.currentTime >= state.practice.end) loopPractice();
    if ($('beep-enabled').checked) tickBeep(current);
  }
  const signed = (value) => `${value > 0 ? '+' : ''}${value}f`;
  function activeTarget() { return state.rows.find((row) => row.id === state.activeRowId)?.frame ?? null; }
  function loadVideo() { if (!isHttpPage()) return setStatus('file://直開きではYouTubeを再生できません。READMEのHTTP起動方法を使ってください', true); const videoId = getVideoId($('video-url').value.trim()); if (!videoId) return setStatus('YouTube URLを確認してください', true); state.videoId = videoId; createPlayer(videoId); setStatus('動画を読み込み中…'); }
  function seek(seconds, play = false) { if (!state.ready) return; state.player.seekTo(Math.max(0, Math.min(state.duration || Infinity, seconds)), true); if (play) state.player.playVideo(); updatePosition(); }
  function loopPractice() { if (!state.practice || !state.ready || state.practice.looping) return; state.practice.looping = true; seek(state.practice.start); state.player.playVideo(); window.setTimeout(() => { if (state.practice) state.practice.looping = false; }, 250); }
  function togglePlay() { if (!state.ready) return; const playing = state.player.getPlayerState() === YT.PlayerState.PLAYING; playing ? state.player.pauseVideo() : state.player.playVideo(); }
  function step(direction) { if (!state.ready) return; state.player.pauseVideo(); seek(state.currentTime + direction / fps()); }
  function startReverse() { if (!state.ready) return; state.player.pauseVideo(); window.clearInterval(state.reverseTimer); state.reverseTimer = window.setInterval(() => { if (state.currentTime <= 0) return window.clearInterval(state.reverseTimer); seek(state.currentTime - 1 / fps()); }, 1000 / 4); }
  function stopReverse() { window.clearInterval(state.reverseTimer); state.reverseTimer = null; }
  function changeSpeed(delta) { const select = $('speed'); const values = [...select.options].map((o) => Number(o.value)); const next = values[Math.max(0, Math.min(values.length - 1, values.indexOf(Number(select.value)) + delta))]; select.value = next; if (state.ready) state.player.setPlaybackRate(next); }
  function capture() { if (!state.ready) return setStatus('動画を読み込んでください', true); const actualFrame = frameAt(state.currentTime); const targetFrame = activeTarget(); const log = { id: id('log'), rowId: state.activeRowId, targetFrame, actualFrame, delta: targetFrame == null ? null : actualFrame - targetFrame, createdAt: new Date().toISOString() }; state.logs.unshift(log); renderLogs(); setStatus(targetFrame == null ? `${actualFrame}f を記録しました` : `${actualFrame}f / 目標との差 ${signed(log.delta)}`); beep(880, .09); }
  function startPractice(rowId, autoplay = true) { state.activeRowId = rowId; const frame = state.rows.find((row) => row.id === rowId)?.frame; if (frame == null) return; stopReverse(); const start = Math.max(0, (frame - 5 * fps()) / fps()); state.practice = { rowId, start, end: (frame + 2 * fps()) / fps(), looping: false }; seek(start, autoplay); renderRows(); }
  function addRow(label = '新しい目標', frame = '') { const row = { id: id('row'), label, frame: frame === '' ? null : Number(frame) }; state.rows.push(row); state.activeRowId = row.id; renderRows(); }
  function addCurrentFrameRow() { if (!state.ready) return setStatus('動画を読み込んでください', true); const current = frameAt(state.currentTime); addRow(`現在 ${formatTime(state.currentTime)}`, current); setStatus(`現在のフレーム ${current}f を目標に追加しました`); }
  function parseNotesToRows() { const lines = $('notes').value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); const parsed = lines.map((label) => { const frameMatch = label.match(/(?:^|\s)(\d+)\s*f\b/i); if (frameMatch) return { label, frame: Number(frameMatch[1]) }; const timeMatch = label.match(/(?:^|\s)(\d{1,3}):(\d{2})(?:\.(\d+))?/); if (!timeMatch) return { label, frame: null }; const seconds = Number(timeMatch[1]) * 60 + Number(timeMatch[2]) + Number(`0.${timeMatch[3] || 0}`); return { label, frame: Math.round(seconds * fps()) }; }); if (!parsed.length) return setStatus('TLの行がありません', true); state.rows.push(...parsed.map((row) => ({ id: id('row'), ...row }))); state.activeRowId = state.rows.at(-1).id; renderRows(); setStatus(`${parsed.length}行を目標行として追加しました`); }
  function renderRows() { const root = $('tl-list'); root.innerHTML = ''; state.rows.forEach((row) => { const item = document.createElement('div'); item.className = `tl-row${row.id === state.activeRowId ? ' active' : ''}`; const label = document.createElement('button'); label.textContent = row.label || '（無題）'; label.title = 'この行を再生'; label.onclick = () => startPractice(row.id); const frame = document.createElement('input'); frame.type = 'number'; frame.min = '0'; frame.placeholder = '目標f'; frame.value = row.frame ?? ''; frame.onchange = () => { row.frame = frame.value === '' ? null : Number(frame.value); render(); }; const remove = document.createElement('button'); remove.className = 'remove'; remove.textContent = '×'; remove.title = '行を削除'; remove.onclick = () => { state.rows = state.rows.filter((candidate) => candidate.id !== row.id); if (state.activeRowId === row.id) state.activeRowId = null; render(); }; item.append(label, frame, remove); root.append(item); }); }
  function renderLogs() { const root = $('log-list'); root.innerHTML = ''; if (!state.logs.length) return root.innerHTML = '<p class="empty">まだログはありません。動画再生中にクリックしてください。</p>'; state.logs.forEach((log) => { const item = document.createElement('div'); item.className = `log-entry ${log.delta != null && Math.abs(log.delta) <= 2 ? 'good' : 'bad'}`; const delta = log.delta == null ? '目標未設定' : signed(log.delta); item.innerHTML = `<div class="log-main"><span>${log.actualFrame.toLocaleString()}f</span><span class="${log.delta != null && Math.abs(log.delta) <= 2 ? 'delta-good' : 'delta-bad'}">${delta}</span></div><div class="log-sub">目標 ${log.targetFrame ?? '—'}f · ${new Date(log.createdAt).toLocaleTimeString('ja-JP')}</div>`; item.onclick = () => { if (log.rowId) startPractice(log.rowId, false); seek(log.actualFrame / fps()); }; root.append(item); }); }
  function render() { renderRows(); renderLogs(); updatePosition(); }
  function exportData() { const data = { version: 1, video: { url: $('video-url').value, fps: fps() }, notes: $('notes').value, rows: state.rows, logs: state.logs }; const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `priconne-ub-practice-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); }
  function importData(file) { const reader = new FileReader(); reader.onload = () => { try { const data = JSON.parse(reader.result); $('video-url').value = data.video?.url || ''; $('fps').value = data.video?.fps || 60; $('notes').value = data.notes || ''; state.rows = Array.isArray(data.rows) ? data.rows : []; state.logs = Array.isArray(data.logs) ? data.logs : []; state.activeRowId = null; render(); setStatus('JSONを読み込みました'); } catch (_) { setStatus('JSONの読み込みに失敗しました', true); } }; reader.readAsText(file); }
  function beep(frequency = 660, duration = .08) { state.audio ||= new (window.AudioContext || window.webkitAudioContext)(); const oscillator = state.audio.createOscillator(); const gain = state.audio.createGain(); oscillator.frequency.value = frequency; gain.gain.setValueAtTime(.035, state.audio.currentTime); gain.gain.exponentialRampToValueAtTime(.001, state.audio.currentTime + duration); oscillator.connect(gain).connect(state.audio.destination); oscillator.start(); oscillator.stop(state.audio.currentTime + duration); }
  function tickBeep(frame) { const second = Math.floor(state.currentTime); if (state.lastBeepSecond !== second) { state.lastBeepSecond = second; beep(); } }
  $('load-video').onclick = loadVideo; $('play').onclick = togglePlay; $('click-capture').onclick = capture; $('back-frame').onclick = () => step(-1); $('forward-frame').onclick = () => step(1); $('reverse').onmousedown = startReverse; $('reverse').onmouseup = stopReverse; $('reverse').onmouseleave = stopReverse; $('speed-down').onclick = () => changeSpeed(-1); $('speed-up').onclick = () => changeSpeed(1); $('speed').onchange = () => state.ready && state.player.setPlaybackRate(Number($('speed').value)); $('volume').oninput = (event) => state.ready && state.player.setVolume(Number(event.target.value)); $('mute').onclick = () => { if (!state.ready) return; state.player.isMuted() ? state.player.unMute() : state.player.mute(); $('mute').textContent = state.player.isMuted() ? '🔇' : '🔊'; }; $('add-row').onclick = () => addRow(); $('add-current-row').onclick = addCurrentFrameRow; $('parse-notes').onclick = parseNotesToRows; $('clear-logs').onclick = () => { state.logs = []; renderLogs(); }; $('export-button').onclick = exportData; $('import-button').onclick = () => $('import-file').click(); $('import-file').onchange = (event) => event.target.files[0] && importData(event.target.files[0]); $('fps').onchange = render; $('beep-enabled').onchange = () => { if (!$('beep-enabled').checked) state.lastBeepSecond = null; };
  document.addEventListener('keydown', (event) => { if (['INPUT', 'TEXTAREA', 'SELECT'].includes(document.activeElement.tagName)) return; if (event.key === ' ' || event.key.toLowerCase() === 'k') { event.preventDefault(); togglePlay(); } else if (event.key === 'j' || event.key === 'ArrowLeft') step(-1); else if (event.key === 'l' || event.key === 'ArrowRight') step(1); else if (event.key === 'Enter') capture(); else if (event.key.toLowerCase() === 'm') $('mute').click(); else if (event.key.toLowerCase() === 'b') { $('beep-enabled').checked = !$('beep-enabled').checked; } else if (event.shiftKey && event.key.toLowerCase() === 'j') startReverse(); });
  window.addEventListener('beforeunload', stopReverse); setStatus(isHttpPage() ? 'YouTube APIを準備中…' : 'file://直開きです。YouTube再生にはHTTP起動が必要です');
})();
