(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const STORAGE_KEY = 'priconner-clan-battle-trainer:damage-review:v1';
  const state = { rows: [], urls: ['', ''], files: ['', ''], objectUrls: ['', ''], playing: false };
  const videos = [$('damage-video-1'), $('damage-video-2')];
  const fps = (index) => Math.max(1, Number.parseFloat($(`damage-fps-${index + 1}`).value) || 60);
  const time = () => { const loaded = videos.filter((video) => video.readyState); return loaded.length ? loaded.reduce((sum, video) => sum + video.currentTime, 0) / loaded.length : 0; };
  const frame = (index, seconds) => Math.max(0, Math.round(seconds * fps(index)));
  const formatTime = (seconds) => { const value = Math.max(0, Number(seconds) || 0); return `${String(Math.floor(value / 60)).padStart(2, '0')}:${(value % 60).toFixed(3).padStart(6, '0')}`; };
  const setStatus = (message, error = false) => { $('damage-status').textContent = message; $('damage-status').style.color = error ? 'var(--bad)' : ''; };
  function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify({ version: 1, fps: [fps(0), fps(1)], rows: state.rows })); }
  function restore() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'); if (!saved) return; $('damage-fps-1').value = saved.fps?.[0] || 60; $('damage-fps-2').value = saved.fps?.[1] || 60; state.rows = Array.isArray(saved.rows) ? saved.rows : []; } catch (_) { localStorage.removeItem(STORAGE_KEY); } }
  function seek(seconds) { videos.forEach((video) => { if (video.readyState) video.currentTime = Math.max(0, Math.min(video.duration || Infinity, seconds)); }); update(); }
  function update() { const current = time(); $('damage-time').textContent = formatTime(current); $('damage-play').textContent = state.playing ? 'Ⅱ 一時停止' : '▶ 再生'; $('damage-empty').hidden = state.rows.length > 0; state.rows.forEach((row) => { const cell1 = document.querySelector(`[data-frame-1="${row.id}"]`); const cell2 = document.querySelector(`[data-frame-2="${row.id}"]`); if (cell1) cell1.textContent = `${frame(0, row.seconds)}f`; if (cell2) cell2.textContent = `${frame(1, row.seconds)}f`; }); }
  function renderRows() { const root = $('damage-rows'); root.innerHTML = ''; state.rows.forEach((row) => { const tr = document.createElement('tr'); const timeCell = document.createElement('td'); const jump = document.createElement('button'); jump.className = 'time-jump'; jump.textContent = formatTime(row.seconds); jump.title = '両方の動画をこの秒数へシーク'; jump.onclick = () => seek(row.seconds); timeCell.append(jump); const damageCells = [1, 2].map((index) => { const td = document.createElement('td'); const input = document.createElement('input'); input.type = 'text'; input.value = row[`damage${index}`] || ''; input.placeholder = '—'; input.oninput = () => { row[`damage${index}`] = input.value; persist(); }; td.append(input); return td; }); const frame1 = document.createElement('td'); frame1.dataset.frame1 = row.id; const frame2 = document.createElement('td'); frame2.dataset.frame2 = row.id; const removeCell = document.createElement('td'); const remove = document.createElement('button'); remove.className = 'remove'; remove.textContent = '×'; remove.title = '行を削除'; remove.onclick = () => { state.rows = state.rows.filter((candidate) => candidate.id !== row.id); persist(); renderRows(); }; removeCell.append(remove); tr.append(timeCell, ...damageCells, frame1, frame2, removeCell); root.append(tr); }); update(); }
  function addRow() { const seconds = Math.max(0, Number(time().toFixed(3))); state.rows.push({ id: `damage-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, seconds, damage1: '', damage2: '' }); state.rows.sort((a, b) => a.seconds - b.seconds); persist(); renderRows(); setStatus(`${formatTime(seconds)} の記録を追加しました`); }
  function loadFile(index, file) { if (!file || !file.type.startsWith('video/')) return setStatus('動画ファイルを選択してください', true); if (state.objectUrls[index]) URL.revokeObjectURL(state.objectUrls[index]); state.objectUrls[index] = URL.createObjectURL(file); state.files[index] = file.name; videos[index].src = state.objectUrls[index]; videos[index].load(); $(`damage-meta-${index + 1}`).textContent = `${file.name}：読み込み中`; }
  function togglePlay() { const shouldPlay = !state.playing; state.playing = shouldPlay; videos.forEach((video) => { if (shouldPlay) video.play().catch(() => {}); else video.pause(); }); update(); }
  function step(direction) { const current = time(); videos.forEach((video, index) => { if (video.readyState) video.currentTime = Math.max(0, Math.min(video.duration || Infinity, current + direction / fps(index))); }); update(); }
  function jump(seconds) { seek(time() + seconds); }
  $('damage-file-1').onchange = (event) => loadFile(0, event.target.files[0]); $('damage-file-2').onchange = (event) => loadFile(1, event.target.files[0]);
  videos.forEach((video, index) => { video.addEventListener('loadedmetadata', () => { $(`damage-meta-${index + 1}`).textContent = `${state.files[index] || `動画${index + 1}`}：${formatTime(video.duration)} / ${Math.round(video.duration * fps(index)).toLocaleString()}f`; update(); }); video.addEventListener('play', () => { state.playing = true; update(); }); video.addEventListener('pause', () => { if (videos.every((candidate) => candidate.paused)) state.playing = false; update(); }); video.addEventListener('timeupdate', update); });
  [$('damage-fps-1'), $('damage-fps-2')].forEach((input) => input.onchange = () => { persist(); renderRows(); });
  $('damage-play').onclick = togglePlay; $('damage-back-frame').onclick = () => step(-1); $('damage-forward-frame').onclick = () => step(1); $('damage-back-5').onclick = () => jump(-5); $('damage-forward-5').onclick = () => jump(5); $('damage-add-row').onclick = addRow;
  $('practice-mode').onclick = () => { $('damage-screen').hidden = true; document.querySelector('.app-shell').hidden = false; $('practice-mode').classList.add('active'); $('damage-mode').classList.remove('active'); };
  $('damage-mode').onclick = () => { $('damage-screen').hidden = false; document.querySelector('.app-shell').hidden = true; $('damage-mode').classList.add('active'); $('practice-mode').classList.remove('active'); update(); };
  restore(); renderRows(); window.addEventListener('beforeunload', () => state.objectUrls.forEach((url) => url && URL.revokeObjectURL(url)));
})();
